preferences:
  keywords:
    must: ["python"]  # antes: ["python","sql"]
    should: ["data","science","analytics","power bi","bigquery","machine learning","entry","junior","sql"]
    nice: ["pandas","numpy","scikit-learn","sklearn","xgboost","matplotlib",
           "looker","looker studio","docker","airflow","fastapi","rest api",
           "education analytics","edtech","nlp","mlops"]
  exclude_keywords: ["senior","lead","principal","staff","architect"]
  remote_only: true
  allowed_countries: ["CO","LATAM","Remote"]
  # work_hours_hint puede quedarse
  work_hours_hint: ["afternoon","americas","utc-5"]

  # ↓ Desactivar por ahora para abrir el embudo; reactivar luego
  # workload: ["part-time","contract","freelance"]
  # seniority: ["junior","entry","intern"]

  languages: ["es","en"]
  cv_path: "docs/CV_Harry_Guevara.pdf"

storage:
  csv_path: "data/jobs.csv"

notifications:
  email:
    enabled: true
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: ""    # lo toma de GitHub Secrets
    password: ""    # lo toma de GitHub Secrets
    to: "harryguevarah@gmail.com"

sources:
  remoteok:
    enabled: true
  weworkremotely:
    enabled: true
  greenhouse:
    enabled: false
    boards: []
  lever:
    enabled: false
    boards: []
  ashby:
    enabled: false
    boards: []
