preferences:
  keywords:
    must: ["python"]
    should: ["data","science","analytics","power bi","bigquery","machine learning","junior","entry level","sql"]
    nice: ["pandas","numpy","scikit-learn","sklearn","xgboost","matplotlib",
           "looker","looker studio","docker","airflow","fastapi","rest api",
           "education analytics","edtech","nlp","mlops"]
  exclude_keywords: ["senior","lead","principal","staff","architect"]
  remote_only: true
  allowed_countries: ["CO","LATAM","Remote"]
  workload: ["part-time","contract","freelance"]
  work_hours_hint: ["afternoon","americas","utc-5"]
  seniority: ["junior","entry","intern"]
  languages: ["es","en"]
  cv_path: "docs/CV_Harry_Guevara.pdf"

storage:
  csv_path: "data/jobs.csv"

notifications:
  email:
    enabled: false
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    to: ""
  telegram:
    enabled: false
    bot_token: ""
    chat_id: ""

sources:
  remoteok:
    enabled: true
  weworkremotely:
    enabled: true
  greenhouse:
    enabled: false
    boards: []
  lever:
    enabled: false
    boards: []
  ashby:
    enabled: false
    boards: []
